### ISSUE TITLE
Wrong sequence

### ISSUE THREAD

**Issue by alyon4a** [learn-co-curriculum/fewpjs-javascript-eventing#7]
We've already discussed callbacks, the text doesn't make sense

**Comment by Sdcrouse** [comment]
I don't know if the curriculum was updated since you posted this issue, but right now callbacks don't seem to be discussed at length (if at all) until after this lesson.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved so I'm going to go ahead and close this issue.

Thanks for contributing to the Flatiron curriculum. 💙
